baseURL = 'ä½ çš„åŸŸå'
languageCode = 'zh'
title = 'æ—¶ç ‚å‡å‡ é¡µ'
theme = 'atlas'
defaultContentLanguage = 'zh'
ignoreFiles = ["æ¨¡æ¿$", ".excalidraw.md$", ".u8$"]
hasCJKLanguage = true
copyright = " 2021-{year} yaleiyale"
pluralizelisttitles = false
[taxonomies]
tag = "tags"
[outputs]
home = ["HTML", "JSON"]
[markup.goldmark.renderer]
unsafe = true
[params.sidebar]
avatarURL = 'https://i.imgur.com/Sx5vDKz.png'
timeFrom = "07/23/2022 10:59:03"
description = '''
ä¹¦äº‹<br>å”Â·ç‹ç»´<br>
  è½»é˜´é˜å°é›¨ï¼Œ
  <a href="mailto:deilookout@outlook.com">
    <i class="fa-solid fa-envelope fa-fw fa-bounce"></i>
  </a>
  <br/>
  æ·±é™¢æ˜¼æ…µå¼€ã€‚
  <a href="https://github.com/yaleiyale">
    <i class="fa-brands fa-github fa-fw fa-bounce"></i>
  </a>
  <br/>
  åçœ‹è‹è‹”è‰²ï¼Œ
  <a href="https://www.acfun.cn/u/31661560">
    <i class="fa-solid fa-otter fa-fw fa-bounce"></i>
  </a>
  <br/>
  æ¬²ä¸Šäººè¡£æ¥ã€‚
  <a href="https://space.bilibili.com/357477198">
    <i class="fa-brands fa-bilibili fa-fw fa-bounce"></i>
  </a>'''
[params.donate]
colaURL = "https://i.imgur.com/9kSi9ER.png"
donateParams = '''
<script>
        var myname = "yaleiyale";
        var profile = "https://i.imgur.com/Sx5vDKz.png";
        var usage = "payment";
        var wechat = "wxp://f2f0dsQlAhlj8JhTvCFKDc06potIJmAlC6Egb5iwzbEuuVA";
        var tenpay = "https://i.qianbao.qq.com/wallet/sqrcode.htm?m=tenpay&f=wallet&a=1&ac=CAEQ_d7U6wgYgpb1lgZCIDk4MGU5NTgxYjYwMmVmMjRhMGI4NzE2OTQzMzEzMWU0_xxx_sign&u=2373267325&n=fidget";
        var alipay = "https://qr.alipay.com/fkx15566l3ytwvk3t7bgd40";
        var paypal = "https://paypal.me/";
        var multilingual = false;
        var branding = false;
        var title = "é€‰æ‹©ä½ çš„æ”¯ä»˜æ–¹å¼";
        var subtitle = "è·Ÿéšè¿›ä¸€æ­¥çš„æŒ‡ç¤ºä»¥å‘" + myname + "ä»˜æ¬¾";
        var qrcodeapi = "https://www.zhihu.com/qrcode?url=";
</script>'''
[params.right]
licenseURL = "https://creativecommons.org/licenses/by/4.0/deed.zh"
licenseName = "CC BY 4.0ï¼ˆé™¤ç‰¹åˆ«å£°æ˜å’Œè½¬è½½ï¼‰"
[params.index]
separatorh = "<!-- .slide -->"
separatorv = "<!-- .slide vertical=true -->"
[params.waline]
reactionTitle = 'REACTION'
placeholder = 'åŒ¿åå¯è¡Œ ä½†è¯´æ— å¦¨'
sofa = 'ğŸˆš'
serverURL = 'https://lestua.cn.eu.org'
reaction = [
  'https://i.imgur.com/8hUUTzl.png',
  'https://i.imgur.com/YwoatB7.png',
  'https://i.imgur.com/8zdTsHc.png',
]
[params]
thumbsup = '''ç”±
<a href="https://gohugo.io/">hugo</a>
<a href="https://obsidian.md/">obsidian</a> é©±åŠ¨'''
[params.music]
server = "netease"
type = "playlist"
id = "7751556455"
order = "random"
lrc = "0"
[params.live2d]
mode = "fixed" #static, static, draggable
hidden = true
link = ["/wormhole"]
skin = ["è¦æ¢æˆæˆ‘çš„æœ‹å‹å—ï¼Ÿ", "è®©å¥¹æ”¾ä¸ªå‡å§~"]
referer = "å“‡å“¦ï¼Œä» %t ç©¿è¶Šæ¥çš„ï¼"
custom = '''[{ "selector": "a", "type": "link" },
{ "selector": "#cola", "text": "æ‰“èµè¦ç†æ€§å“¦ğŸ˜»" },
{ "selector": "img:not(#lamuimg, #leimuimg)", "text": "clickğŸ‰" },
{ "selector": ".wl-reaction", "text": "æˆ‘æ¥è¦èµå’¯ğŸŒŸ" },
{ "selector": "#wl-edit", "text": "æ–‡æ˜å‘è¨€ï¼Œä¸ç„¶ä¼šè¢«ğŸš«å“¦" },
{ "selector": "#wl-mail", "text":"å¡«é‚®ç®±å¯ä»¥æ˜¾ç¤ºGravatarï¼Œæ”¶åˆ°è¯„è®ºå›å¤é‚®ä»¶æé†’å“¦ğŸ‰"},
{ "selector": ".highlight", "text": "ä»£ç å¯ä»¥ä¸€é”®å¤åˆ¶å‘¢ğŸ”–" },
{ "selector": ".sidebar-toggle", "text": "æ‰“å¼€ä¾§è¾¹æ å­ğŸ—‚ï¸" },
{ "selector": ".effect-info", "text": "å“‡ï¼Œä½ å‘ç°äº†ä»€ä¹ˆâ—" },
{ "selector": "#sidebar-search-input", "text": "æƒ³æœç´¢ä»€ä¹ˆå‘¢â“" },
{ "selector": ".note-title", "text": "è¿™æ˜¯æ ‡é¢˜âœ¨" },
{ "selector": ".article-nav", "text": "å†é€›ä¸€ä¼šå­ğŸˆ~" },
{ "selector": ".social-share", "text": "åˆ†äº«åˆ†äº«ğŸ˜" }]'''
model = [
  "https://lestua.eu.org/web_kanbanniang_collection/umaru/model.json",
  "https://lestua.eu.org/web_kanbanniang_collection/rem/model.json",
  "https://lestua.eu.org/web_kanbanniang_collection/koharu/model.json",
  "https://lestua.eu.org/web_kanbanniang_collection/kurumi/model.json",
]
[[menu.main]]
name = '<i class="fa-solid fa-comment fa-fw"></i> ç•™è¨€'
url = "/board"
weight = "1"
[[menu.main]]
name = '<i class="fa-solid fa-seedling fa-fw"></i> èšç‚¹'
url = '/road'
weight = "2"
[[menu.main]]
name = '<i class="fa-solid fa-archive fa-fw"></i> å½’æ¡£'
url = '/archive'
weight = "3"
[[menu.main]]
name = '<i class="fa-solid fa-tags fa-fw"></i> æ ‡ç­¾'
url = '/tags'
weight = "4"
[[menu.main]]
name = '<i class="fa-solid fa-circle-nodes fa-fw"></i> å›¾è°±'
url = '/atlas'
weight = "5"
[[menu.main]]
name = '<i class="fa-solid fa-coffee fa-fw"></i> æ‰“èµ'
url = '/donate'
weight = "6"
